project_id = "jhakdiqttnvwczyzoffu"

[functions.analyze-candidate]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.analyze-interview]
verify_jwt = false

[functions.generate-interview-questions]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false

[functions.delete-job-cascade]
verify_jwt = false

[functions.compare-candidates]
verify_jwt = false

[functions.generate-presentation-report]
verify_jwt = false

[functions.send-executive-report]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.generate-linkedin-post]
verify_jwt = false

[functions.create-recruiters]
verify_jwt = false

[functions.send-test-emails]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
