project_id = "jhakdiqttnvwczyzoffu"

[functions.analyze-candidate]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.generate-interview-questions]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false
